### ISSUE TITLE
AttributeError: 'module' object has no attribute 'readim7'

### ISSUE THREAD

**Issue by fbl1991** [FabricioS/libim7#1]
I did as the following. My system is Mac. When running the test_IMX.py, I get the errors "AttributeError: 'module' object has no attribute 'readim7'". What's wrong?

**Comment by FabricioS** [comment]
Can you please post the full traceback?

**Comment by fbl1991** [comment]
Thanks. Here is:
Traceback (most recent call last):
  File "test_IMX.py", line 35, in <module>
    buf1, att1 = im7.readim7(fname)
AttributeError: 'module' object has no attribute 'readim7'

**Comment by FabricioS** [comment]
Thank you for this tiny traceback.
Can you describe your python installation (py2/3 windows/linux) ?
Did you extension build correctly ?
Is there a compiled extension file _im7.....{so or pyd} in the libim7 folder ?

Running the test script in an interactive shell, can you tell me the output of
>>> im7.mylib 
On my machine, it is 
<CDLL '.../src/libim7/libim7/_im7.so', handle 26990 at 0x7f6389733>

**Comment by fbl1991** [comment]
My python is 2.7. No errors appeared during the building. The _im7.so file is in the libim7 folder. 
But which test script should I run? 
Thanks

**Comment by FabricioS** [comment]
Can you tell the content of the im7 object after the error ?
>> print(type(im7), dir(im7))

You can try the test_SOV2_...py, but I suspect you will have the same error as the import of the module im7 is similar.

**Comment by fbl1991** [comment]
Ok. Here it is. 
(<type 'module'>, ['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__'])
None readim7 method appeares.

**Comment by fbl1991** [comment]
Ok. Here it is. 
(<type 'module'>, ['\__builtins__', '\__doc__', '\__file__', '\__name__', '\__package__', '\__path__'])
None readim7 method appeares.

**Comment by FabricioS** [comment]
In fact, I have been misleadingly importing libim7 in tests.

It does work if you run the scripts from within the test folder, and it does because the path to the folder containing the libim7.py file is added to sys.path. Note that it does not import libim7 as a package (i.e. the libim7 folder containing the __init__.py) but as a module (the libim7.py file).

I should correct that by adding some stuff in the __init__.py file to give access to the readim7 function when you load the package (and not directly the module).

Temporarily, you can work from within the test folder, or correct the path appended to sys.path at the beginning of the script to point to the folder containing libim7.py

**Comment by FabricioS** [comment]
Can you test with the last commit 99feb343e0d ?

**Comment by fbl1991** [comment]
Thank you. It works now. HAHA.
But, when I have run the installation command. The _im7.so wasn't copied to the python library folder. Thus, I got the error 'OSError: dlopen(/Library/Python/2.7/site-packages/libim7/_im7.so, 6): image not found'. So I copy it manually.  Could you tell me why?

**Comment by FabricioS** [comment]
Any error message during the installation ? Maybe something like
> creating /Library/Python/2.7/site-packages/libim7
> error: could not create '/Library/Python/2.7/site-packages/libim7': Permission denied

**Comment by fbl1991** [comment]
No. I always do this with sudo

**Comment by FabricioS** [comment]
Ok it seems to be another issue due to a old-school setup.py. I move your comment to issue #2.
